# Introduction to Julia and IJulia/Jupyter
<table>
<tr>
<td> <a href="http://julialang.org"><img src="src/figures/julia.png" alt="Julia" style="width: 150px;"/></a></td>
<td> <a href="http://jupyter.org"><img src="src/figures/jupyter.png" alt="Jupyter" style="width: 150px;"/></a></td>
<td> <a href="https://github.com/JuliaLang/IJulia.jl"><img src="src/figures/ijulia.png" alt="IJulia" style="width: 150px;"/></a></td>
</tr></table>

This notebook is an introduction to the language **Julia**, and the use of the IJulia/Jupyter notebook in a statistics/optimization workflow. It is meant to be presented in 1 hour.
The Julia language will be introduced quickly, the aim is to motivate the readers to learn the language by themselves using more thorough teaching material

## Why using Julia?
We introduce in this section **Julia**, a fast programming language that is particularly good at scientific computing.
<a href="http://julialang.org"><img src="src/figures/julia.png" alt="Julia" style="width: 150px;"/></a>

Quoting the [Julia website](http://julialang.org):
> Julia is a **high-level**, **high-performance** **dynamic** programming language for **technical computing**, with syntax that is familiar to users of other technical computing environments. It provides a sophisticated compiler, distributed parallel execution, numerical accuracy, and an extensive mathematical function library.

**High-level** language

- The syntax is easy to use and learn. It will seem familiar to Python and Matlab users. It is possible to do complicated computations quickly.

- Solving $Ax = b$ with 
$A = \begin{pmatrix}
 1 & 2 & 3\\ 
 2 & 1 & 2\\ 
 3 & 2 & 1
\end{pmatrix}$
and $b = \begin{pmatrix}
 1 \\ 
 1 \\ 
 1 
\end{pmatrix}$
is as simple as:

In [1]:
A = [1 2 3
     2 1 2
     3 2 1]

b = [1,1,1]
A\b

3-element Array{Float64,1}:
  0.25
 -0.0 
  0.25

A **dynamic** language:

- Julia is, like Python, Matlab or R, a dynamic language: you can interact with the language without the need to compile your code. Static or compiled languages, like C or Fortran, are more complicated to use but generally faster, and thus used when there is a need for time-efficient computations. 

- This is the _two-languages problem_: one generally use a high level language for research and scripting, and then translate the final result in a static language for performance.

A **High Performance** language:
- Julia solves the two languages problem using **just-in-time compilation**. While running, your code will be automatically compiled and optimized to reach performances comparable to static languages like C, Fortran and Go.
- Unlike R, Matlab or Python, simple loops are extremely efficient in Julia:

In [2]:
function countTo(n)
    count = 0
    for i = 1:n
        count += 1
    end
    return count
end
println("First use: slow like a dynamic language")
@time countTo(10_000_000)
println("Second use: compiled and optimized automatically")
@time countTo(10_000_000);

First use: slow like a dynamic language
  0.006397 seconds (1.52 k allocations: 72.265 KB)
Second use: compiled and optimized automatically
  0.000001 seconds (5 allocations: 176 bytes)


A language for **technical computing**
- Julia has a lot of built in functions for scientific computing.
- A growing number of packages, mostly written in Julia itself.
- More and more users in Finance, Biology, Optimization.
- Can run C and Python code seemlessly (using Scikit for Machine Learning...)


## Jupyter/IJulia notebook basics
We present, install and use the Jupyter notebooks, a formidable tool made available to Julia by the IJulia project.

### What is a Jupyter Notebook?
- Jupyter notebooks are **documents** (a little like a Word document) that can contain and run code.
- They were originally created for Python in the IPython projects, and adapted to Julia by the **IJulia** project.
- They are very useful to **prototype**, draw **plots**, or even for teaching material like this one.
- The document relies only on a modern browser for rendering, and can easily be **shared**.

### Installing IJulia and loading this notebook
Once Julia is installed, start julia and just run the following command to install the `IJulia` package
```jl
Pkg.install("IJulia")
```
This should work on its own. If there is any issue, check out the [IJulia website](https://github.com/JuliaLang/IJulia.jl).

Once IJulia is installed, go to the notebook file (_.ipynb_) directory, start julia and run:
```jl
using IJulia
notebook()
```
A webpage should open automatically, just click on the notebook to load it.

### Navigating the notebook

- Click `Help -> User Interface Tour` for a guided tour of the interface.
- Each notebook is composed of **cells**, that either contain code or text (`Markdown`).
- You can edit the content of a cell by double-clicking on it (_Edit Mode_).

When you are not editing a cell, you are in _Command mode_ and can edit the structure of the notebook (cells, name, options...):
- Create a cell by:
    - Clicking `Insert -> Insert Cell`
    - Pressing `a` or `b` in Command Mode
    - Pressing `Alt+Enter` in Edit Mode
- Delete a cell by:
    - Clicking `Edit -> Delete Cell`
    - Pressing `dd`
- Execute a cell by:
    - Clicking `Cell -> Run`
    - Pressing `Ctrl+Enter`

Other functions:
- Undo last text edit with `Ctrl+z` in Edit Mode
- Undo last cell manipulation with `z` in Command Mode
- Save notebook with `Ctrl+s` in Edit Mode
- Save notebook with `s` in Command Mode

Though notebooks rely on your browser to work, they do not require an internet connection (except for math rendering).


### Get comfortable with the notebook
Notebooks are designed to not be fragile. If you try to close a notebook with unsaved changes, the browser will warn you.

Try the following exercises:

>**\[Exercise\]**: Close/open

>1. Save the notebook
>2. Copy the address
>3. Close the tab
>4. Paste the address into a new tab (or re-open the last closed tab with `Ctrl+Shift+T` on Chrome)

>_The document is still there, and the Julia kernel is still alive! Nothing is lost._

>**\[Exercise\]**: Zoom

>Try changing the magnification of the web page (`Ctrl+, Ctrl-` on Chrome).

>_Text and math scale well (so do graphics if you use an SVG or PDF backend)._

>**\[Exercise\]**: MathJax
>1. Create a new cell, and select the type `Markdown` (or press `m`)
>2. Type an opening \$, your favorite mathematical expression, and a closing \$.
>3. Run the cell to render the $\LaTeX$ expression.
>4. Right-click the rendered expression.

## Coding in Julia
This section is a brief introduction to Julia. It is not a comprehensive tutorial but more a _taste_ of the language for those who do not know it, and a showcase of cool features for those who already know Julia.

Very good [tutorials](http://julialang.org/learning/) are available online and in books if you are interested in learning the language.

### Basic use
Julia, as a dynamic language, can simply be used as a calculator:

In [12]:
1+1

2

In [13]:
sin(exp(2*pi)+sqrt(3))

-0.01136232398070678

The building blocs of Julia code are variables:

In [3]:
a = 1
b = 2
# This is a comment 
c = a^2 + b^3 

9

Julia supports the common `if`, `while` and `for` structures:

In [4]:
if c >= 10
    print("Joey")
else
    print("Huchette")
end

Huchette

In [5]:
i = 1
while i <= 5
    println("Joey!") # Print with a new line
    i += 1
end

Joey!
Joey!
Joey!
Joey!
Joey!


In [6]:
for i = 1:3
    print("$i Joey") # '$' can be used to insert variables into text
    if i>1
        print("s")
    end
    println() # Just a new line
end

1 Joey
2 Joeys
3 Joeys


**Do not worry about writing loops**: in Julia, they are as fast as writing vectorized code, and sometimes faster!

**Arrays** (list of numbers) are at the core of research computing and Julia's arrays are extremely optimized.

In [9]:
myList = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

Array indexing starts with 1 in Julia:

In [10]:
myList[1]

1

In [11]:
myList[3] = 4
myList

3-element Array{Int64,1}:
 1
 2
 4

A 2-dimensional array is a Matrix

In [14]:
A = [1 2 3
     2 1 2
     3 2 1]

A = [1 2 3; 2 1 2; 3 2 1] #same thing

3×3 Array{Int64,2}:
 1  2  3
 2  1  2
 3  2  1

Matrix can be multiplied, inversed...

In [15]:
A^-1 #inverse

A^2 * A^-1

3×3 Array{Float64,2}:
 1.0  2.0  3.0
 2.0  1.0  2.0
 3.0  2.0  1.0

In [16]:
A*[1,2,3]

3-element Array{Int64,1}:
 14
 10
 10

In [17]:
eigenValues, eigenVectors = eig(A)
eigenValues

3-element Array{Float64,1}:
 -2.0     
 -0.701562
  5.70156 

**Types:** Everything has a type in Julia

In [18]:
typeof(1)

Int64

In [19]:
typeof(1.5)

Float64

In [20]:
typeof("abc")

String

Types are at the core of Julia's performance. **[multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch)** is used dynamically when a function is called, selecting the right version of the function depending on the type of its argument.

In [21]:
1//2

1//2

In [22]:
typeof(1//2)

Rational{Int64}

In [23]:
(1//2)^2

1//4

In [24]:
(0.5)^2 # The same function gives different results depending on the type

0.25

In [25]:
(im)^2 # This also works with complex numbers

-1 + 0im

In [26]:
function myFunction(x)
    println("Julia!")
end

function myFunction(x::Int) # only called when x is an integer
    println("IJulia!")
end

myFunction(1.0)
myFunction(1)
myFunction("Joey")

Julia!
IJulia!
Julia!


A lot more functionalities are available and for you to discover!

In [27]:
l = [i^2 for i in 1:10 if i%2 == 0] # list comprehensions (similar to Python)

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

### Navigating Julia
Julia has a package manager to quickly download, install, update and uninstall new tools (_packages_)

In [ ]:
# Add Packages Plots, and Pyplot (can take some time)
Pkg.add("Plots")
Pkg.add("PyPlot")
# Update
Pkg.update()
#Remove:
# Pkg.rm("PyPlot")

Use `?` to get the documentation of a function

In [28]:
?eig

search: eig eigs eigmin eigmax eigvecs eigvals eigfact eigvals! eigfact!



```
eig(A,[irange,][vl,][vu,][permute=true,][scale=true]) -> D, V
```

Computes eigenvalues (`D`) and eigenvectors (`V`) of `A`. See [`eigfact`](:func:`eigfact`) for details on the `irange`, `vl`, and `vu` arguments and the `permute` and `scale` keyword arguments. The eigenvectors are returned columnwise.

```jldoctest
julia> eig([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])
([1.0,3.0,18.0],
[1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0])
```

`eig` is a wrapper around [`eigfact`](:func:`eigfact`), extracting all parts of the factorization to a tuple; where possible, using [`eigfact`](:func:`eigfact`) is recommended.

```
eig(A, B) -> D, V
```

Computes generalized eigenvalues (`D`) and vectors (`V`) of `A` with respect to `B`.

`eig` is a wrapper around [`eigfact`](:func:`eigfact`), extracting all parts of the factorization to a tuple; where possible, using [`eigfact`](:func:`eigfact`) is recommended.

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> eig(A, B)
(Complex{Float64}[0.0+1.0im,0.0-1.0im],
Complex{Float64}[0.0-1.0im 0.0+1.0im; -1.0-0.0im -1.0+0.0im])
```


Use tab-completion to auto-complete functions and variables names: try ``myF<TAB>``:

In [ ]:
myF
fac

The ``methods`` function lists all of the different implementations of a function depending on the input types.
Click on the link to see the Julia source code.

In [29]:
methods(sin)

# 10 methods for generic function "sin":
sin(x::BigFloat) at mpfr.jl:610
sin(a::Complex{Float16}) at math.jl:480
sin(a::Float16) at math.jl:479
sin(x::Float32) at math.jl:203
sin(x::Float64) at math.jl:202
sin{T}(z::Complex{T}) at complex.jl:575
sin(x::Real) at math.jl:204
sin{Tv,Ti}(A::SparseMatrixCSC{Tv,Ti}) at sparse/sparsematrix.jl:1347
sin{Tv<:Number,Ti<:Integer}(x::AbstractSparseArray{Tv,Ti,1}) at sparse/sparsevector.jl:853
sin{T<:Number}(x::AbstractArray{T,N<:Any}) at operators.jl:555

### Plotting in IJulia

Julia has a lot of available 

## Advanced use of Julia and Notebooks
Here list of tip/tricks for advanced users
- Github && sharing (gist)
- Slides
- Command line (;)
- Jupyter command line (??)
- Advanced Markdown, LaTeX, code highlighting?
- Possibility of running notebook on remote computer
- Unicode characters
- cool packages
- Juno
- macro, advanced language features...
- Interactivity

## Footnote about adapted material

## Plotting
There are several Julia plotting packages. 

* [PyPlot.jl][4] is a Julia interface to Matplotlib, and should feel familiar to both MATLAB and Python users.
* [Winston][3] and [Gadfly][1] are written entirely in Julia.  Winston is for general-purpose 2D plotting, and Gadfly (inspired by ggplot2) concentrates on statistical graphics.
* [Plotly supports Julia][2].

[1]: https://github.com/dcjones/Gadfly.jl
[2]: https://plot.ly/julia/
[3]: https://github.com/nolta/Winston.jl
[4]: https://github.com/stevengj/PyPlot.jl

In [ ]:
using PyPlot

# Example from PyPlot documentation:
x = linspace(0,2*pi,1000)
y = sin(3*x + 4*cos(2*x))
plot(x, y,  color="red", 
            linewidth=2.0, 
            linestyle="--")
title("A sinusoidally modulated sinusoid");

## Sharing notebooks

Notebooks are self contained and standalone (unless they explicitly ``include()`` other Julia code). You can email them to friends, professors, and even post them online in viewable read-only form.

_Click `File -> Download as -> IPython Notebook (.ipynb)` to save a copy of the notebook._

>**\[Exercise\]**: Share your code

> 1. Create a new notebook with some text, figures, and code.
> 2. Save it to your desktop.
> 3. Open the .ipynb file with a text editor, select all the text and copy it to the clipboard.
> 4. Open [gist.github.com](https://gist.github.com/) and paste the text.
> 5. Name the file foo.ipynb and click "Create public Gist".
> 6. On the next page, click on "Raw".
> 7. Copy the URL to the clipboard and open a new tab with [nbviewer](http://nbviewer.ipython.org/).
> 8. Paste the URL to the raw ipynb into the text box and click "Go!"

> _You now have an emailable link to share your notebook. An installation of IJulia is not required to view it!_

The ``http://nbviewer.ipython.org/urls/..`` link is permanent so long as the original source (gist) exists.

-------

Some content in this notebook was adapted from materials by [Jonas Kersulis](https://github.com/kersulis/IJulia-WPS)